CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_insertNewBookingByGender`(
in IN_FULL_NAME varchar(45),
in IN_GENDER varchar(45),
in IN_BOOKING_SLOT varchar(45),
in IN_ROOM_ID int,
in IN_CHECK_IN_TIME varchar(45),
in IN_CHECK_OUT_TIME varchar(45),
in IN_ADD_MEMBERS INT )
BEGIN
 
 IF IN_GENDER='MALE'THEN
		BEGIN
      IF EXISTS (SELECT ROOM_CUR_EXISTINGGENDER FROM room_details.room_availability WHERE ROOM_CUR_EXISTINGGENDER= 'MALE' AND ROOM_ID=IN_ROOM_ID)THEN
      BEGIN
		INSERT INTO room_details.room_bookinginfo (FULL_NAME,GENDER,BOOKING_SLOT,ROOM_ID,CHECK_IN_TIME,CHECK_OUT_TIME,ADD_MEMBERS) VALUES (IN_FULL_NAME,IN_GENDER,IN_BOOKING_SLOT,IN_ROOM_ID,IN_CHECK_IN_TIME,IN_CHECK_OUT_TIME,IN_ADD_MEMBERS) ;
		
					end;
				else
					BEGIN
						SELECT ROOM_ID,ROOM_CUR_EXISTINGGENDER
						FROM   room_details.room_availability ORDER BY RSI_NO;
    
					end ;
				END IF;
  
		END;
ELSE 
  
  
	 IF IN_GENDER='FEMALE'THEN
		BEGIN
     IF EXISTS (SELECT ROOM_CUR_EXISTINGGENDER FROM room_details.room_availability WHERE ROOM_CUR_EXISTINGGENDER= 'FEMALE' AND ROOM_ID=IN_ROOM_ID)THEN
      BEGIN
		INSERT INTO room_details.room_bookinginfo (FULL_NAME,GENDER,BOOKING_SLOT,ROOM_ID,CHECK_IN_TIME,CHECK_OUT_TIME,ADD_MEMBERS) VALUES (IN_FULL_NAME,IN_GENDER,IN_BOOKING_SLOT,IN_ROOM_ID,IN_CHECK_IN_TIME,IN_CHECK_OUT_TIME,IN_ADD_MEMBERS) ;
		
    
						end;
				   else
						BEGIN
								SELECT ROOM_ID,ROOM_CUR_EXISTINGGENDER
						FROM   room_details.room_availability ORDER BY RSI_NO;
    
						end ;
				   end IF;
			   END;
		END IF;
END IF;
END