CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_checkmaxsize`(IN IN_ROOM_ID INT,
IN IN_ROOM_CUR_COUNT int)
BEGIN
  IF   IN_ROOM_CUR_COUNT<=3 THEN
	BEGIN
		IF IN_ROOM_CUR_COUNT=0 OR IN_ROOM_CUR_COUNT=1 OR IN_ROOM_CUR_COUNT=2 OR IN_ROOM_CUR_COUNT=3  THEN
			BEGIN
				SELECT ROOM_ID,ROOM_CURRENTCOUNT,ROOM_ALLOWEDCOUNT,ROOM_STATUS,ROOM_CUR_EXISTINGGENDER,ROOM_CUR_ALLOWEDGENDER FROM room_details.room_availability WHERE ROOM_ID=IN_ROOM_ID AND ROOM_ALLOWEDCOUNT=IN_ROOM_CUR_COUNT;
			END;
		ELSE
			BEGIN
				SELECT ROOM_ID,ROOM_CURRENTCOUNT FROM room_details.room_availability ;
            END;
		END IF;
	END;
 else
	IF  IN_ROOM_CUR_COUNT>3 THEN
			BEGIN
				SELECT ROOM_STATUS FROM room_details.room_availability ;
            END;
	END IF;
 END IF;
        
END